[build]
  functions = "netlify/functions"
  publish = "dist" # or "build" or "public" depending on your framework setup

[[redirects]]
  from = "/api/speak"
  to = "/.netlify/functions/speak"
  status = 200

[[redirects]]
  from = "/api/whisper"
  to = "/.netlify/functions/whisper"
  status = 200

